# Generated by Django 6.0.5 on 2026-06-13 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_stores', '0003_remove_demo_catalog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='Dam_stores.productitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='Dam_stores__created_bfa046_idx'), models.Index(fields=['expiry_date'], name='Dam_stores__expiry__b890b6_idx'), models.Index(fields=['product_item', 'created_at'], name='Dam_stores__product_dd7488_idx')],
            },
        ),
    ]
