# Generated by Django 6.0.5 on 2026-06-13 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_stores', '0004_productstockentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_date', models.DateField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_sales_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sales_date'],
                'indexes': [models.Index(fields=['sales_date'], name='Dam_stores__sales_d_7ed0f9_idx')],
            },
        ),
    ]
