# Generated by Django 6.0.5 on 2026-06-14 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_stores', '0005_dailysalesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AUDIT', 'Audit'), ('EXPIRY', 'Expiry')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('source_key', models.CharField(max_length=160, unique=True)),
                ('link', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='Dam_stores__created_884133_idx'), models.Index(fields=['kind'], name='Dam_stores__kind_8d9a2b_idx')],
            },
        ),
    ]
