# Generated by Django 6.0.5 on 2026-06-14 05:17

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_admin_users(apps, schema_editor):
    Role = apps.get_model("Dam_stores", "Role")
    User = apps.get_model("Dam_stores", "User")
    admin_role, _ = Role.objects.get_or_create(
        code="ADMIN",
        defaults={
            "name": "Admin",
            "description": "Full access administrator",
            "is_active": True,
        },
    )
    users = [
        ("84364 61226", "Dibakar Dam", "84364 61226", "Dibakar@123"),
        ("85977 81336", "Vaskar Dam", "85977 81336", "Vaskar@123"),
        ("861 755 8509", "Sourav Dam", "861 755 8509", "Sourav@123"),
    ]
    for username, name, mobile, password in users:
        User.objects.update_or_create(
            username=username,
            defaults={
                "name": name,
                "mobile_number": mobile,
                "role": admin_role,
                "is_active": True,
                "is_staff": True,
                "is_superuser": True,
                "password": make_password(password),
            },
        )


def remove_admin_users(apps, schema_editor):
    User = apps.get_model("Dam_stores", "User")
    User.objects.filter(username__in=["84364 61226", "85977 81336", "861 755 8509"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_stores', '0006_inappnotification'),
    ]

    operations = [
        migrations.RunPython(seed_admin_users, remove_admin_users),
    ]
