# Generated by Django 6.0.5 on 2026-06-14 05:18

from django.db import migrations


def backfill_audit_notifications(apps, schema_editor):
    AuditLog = apps.get_model("Dam_stores", "AuditLog")
    InAppNotification = apps.get_model("Dam_stores", "InAppNotification")
    actions = {"CREATE", "UPDATE", "DELETE", "PRICE_CHANGE", "STOCK_CHANGE"}
    for audit in AuditLog.objects.select_related("user").filter(action__in=actions):
        user_label = audit.user.name if audit.user and audit.user.name else audit.user.username if audit.user else "System"
        message = f"{user_label} performed {audit.get_action_display()} on {audit.object_label}"
        notification, created = InAppNotification.objects.get_or_create(
            source_key=f"audit:{audit.pk}",
            defaults={
                "kind": "AUDIT",
                "message": message[:300],
                "actor_id": audit.user_id,
                "link": "/stock/history/",
            },
        )
        if created:
            InAppNotification.objects.filter(pk=notification.pk).update(created_at=audit.created_at)


def remove_backfilled_audit_notifications(apps, schema_editor):
    InAppNotification = apps.get_model("Dam_stores", "InAppNotification")
    InAppNotification.objects.filter(source_key__startswith="audit:").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_stores', '0007_seed_requested_admin_users'),
    ]

    operations = [
        migrations.RunPython(backfill_audit_notifications, remove_backfilled_audit_notifications),
    ]
