# Generated by Django 6.0.5 on 2026-06-20 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_stores', '0008_backfill_audit_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(max_length=180)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['supplier_name'],
                'indexes': [models.Index(fields=['supplier_name'], name='Dam_stores__supplie_eca158_idx'), models.Index(fields=['mobile_number'], name='Dam_stores__mobile__7167bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier_name', 'mobile_number'), name='unique_supplier_name_mobile')],
            },
        ),
        migrations.CreateModel(
            name='DamagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damaged_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_damaged_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_records', to='Dam_stores.productitem')),
            ],
            options={
                'db_table': 'damaged_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='damaged_pro_product_477e00_idx'), models.Index(fields=['created_at'], name='damaged_pro_created_e67433_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_transactions', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Dam_stores.supplier')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['supplier'], name='Dam_stores__supplie_ff7b22_idx'), models.Index(fields=['transaction_date'], name='Dam_stores__transac_3dd1f6_idx')],
            },
        ),
    ]
